os:
  - linux
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - cd delphi2csharp/test1
  - python ../idl2pasintf.py test1.idl
  - python ../idl2pasdllhandler.py test1.idl
  - python ../idl2pasimpl2cdll.py test1.idl
  - python ../idl2csintf.py test1.idl

